#!/usr/bin/env bash
# PermissionRequest hook — auto-approve safe operations, auto-deny dangerous ones
# Generated by /hooks:permission-request-hook for MCU Tinkering Lab
#
# Toggle: set CLAUDE_HOOKS_DISABLE_PERMISSION_REQUEST=1 to skip
#
# Decisions:
#   approve  → tool runs without user prompt
#   deny     → tool blocked, reason shown to Claude
#   (no output) → user prompted as normal (passthrough)

set -euo pipefail

# Toggle off
[ "${CLAUDE_HOOKS_DISABLE_PERMISSION_REQUEST:-}" = "1" ] && exit 0

INPUT=$(cat)

TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // empty')
COMMAND=$(echo "$INPUT" | jq -r '.tool_input.command // empty')

approve() { echo "{\"decision\": \"approve\", \"reason\": \"$1\"}"; exit 0; }
deny()    { echo "{\"decision\": \"deny\", \"reason\": \"$1\"}"; exit 0; }

# ══════════════════════════════════════════════════════════════
# AUTO-APPROVE: Safe, read-only operations
# ══════════════════════════════════════════════════════════════

# Non-Bash tools that are always safe
case "$TOOL_NAME" in
  Read|Glob|Grep) approve "Read-only tool" ;;
esac

# Only process Bash commands below
[ "$TOOL_NAME" != "Bash" ] && exit 0
[ -z "$COMMAND" ] && exit 0

# ── Git: read-only operations ──
if echo "$COMMAND" | grep -Eq '^\s*git\s+(status|log|diff|branch|remote|show|blame|shortlog|describe|ls-files|rev-parse|rev-list|stash\s+list|tag\s+-l|fetch)\b'; then
  approve "Read-only git operation"
fi

# ── Test runners ──
if echo "$COMMAND" | grep -Eq '^\s*(pytest|python\s+-m\s+pytest|uv\s+run\s+(pytest|test))\b'; then
  approve "Python test execution"
fi

# ── Linters and formatters (check/read-only mode) ──
if echo "$COMMAND" | grep -Eq '^\s*(ruff\s+check|mypy|pyright|cppcheck)\b'; then
  approve "Linter/type check"
fi

# ── Format checkers (non-destructive) ──
if echo "$COMMAND" | grep -Eq '^\s*(ruff\s+format\s+--check|clang-format\s+--output-replacements-xml)\b'; then
  approve "Format check (read-only)"
fi

# ── Pre-commit (check only) ──
if echo "$COMMAND" | grep -Eq '^\s*pre-commit\s+(run|install)'; then
  approve "Pre-commit hook management"
fi

# ── Build and compilation (firmware + simulation) ──
if echo "$COMMAND" | grep -Eq '^\s*(make|idf\.py|just)\b'; then
  approve "Build command (make/idf.py/just)"
fi

if echo "$COMMAND" | grep -Eq '^\s*uv\s+run\s+(build|test)'; then
  approve "uv build/test command"
fi

# ── GitHub CLI: read operations ──
if echo "$COMMAND" | grep -Eq '^\s*gh\s+(pr\s+(view|checks|list|diff)|issue\s+(view|list)|run\s+(view|list))\b'; then
  approve "GitHub CLI read operation"
fi

# ── Package info queries ──
if echo "$COMMAND" | grep -Eq '^\s*(pip\s+list|pip\s+show|uv\s+pip\s+list|uv\s+tree)\b'; then
  approve "Package info query"
fi

# ── Python environment inspection ──
if echo "$COMMAND" | grep -Eq '^\s*(python3?\s+--version|which\s+python|python3?\s+-c\s+)'; then
  approve "Python environment inspection"
fi

# ── Device info (esptool read-only) ──
if echo "$COMMAND" | grep -Eq '^\s*esptool\.py\s+(read_mac|chip_id|read_flash|version)\b'; then
  approve "Device read-only operation"
fi

# ── Hardware query commands ──
if echo "$COMMAND" | grep -Eq '^\s*(ls|cat|find|head|tail|grep|file|stat)\s'; then
  approve "File/hardware query operation"
fi

# ══════════════════════════════════════════════════════════════
# AUTO-DENY: Dangerous operations
# ══════════════════════════════════════════════════════════════

# Destructive filesystem operations on root or home
# shellcheck disable=SC2016
if echo "$COMMAND" | grep -Eq 'rm\s+(-[a-zA-Z]*f[a-zA-Z]*\s+)(/($|\s)|/\*|~/|\$HOME)'; then
  deny "Destructive operation on root or home directory"
fi

# Force push to protected branches
if echo "$COMMAND" | grep -Eq 'git\s+push\s+.*--force.*\s(main|master)\b'; then
  deny "Force push to protected branch"
fi

# Insecure permissions
if echo "$COMMAND" | grep -Eq 'chmod\s+777\b'; then
  deny "Insecure permissions (chmod 777)"
fi

# Piped network execution
if echo "$COMMAND" | grep -Eq '(curl|wget)\s.*\|\s*(bash|sh|zsh)'; then
  deny "Piped network execution (curl|bash)"
fi

# Fork bombs
if echo "$COMMAND" | grep -Eq ':\(\)\s*\{.*:\|:.*\}'; then
  deny "Fork bomb detected"
fi

# Block device writes
if echo "$COMMAND" | grep -Eq '(dd\s+.*of=/dev/|>\s*/dev/sd)'; then
  deny "Direct block device write"
fi

# Filesystem formatting
if echo "$COMMAND" | grep -Eq '^\s*mkfs\b'; then
  deny "Filesystem format operation"
fi

# Destructive git clean
if echo "$COMMAND" | grep -Eq '^\s*git\s+clean\s+-[a-zA-Z]*f[a-zA-Z]*d'; then
  deny "Destructive git clean"
fi

# Database destructive operations
if echo "$COMMAND" | grep -Eiq '(psql|mysql|sqlite3).*\b(DROP\s+(DATABASE|TABLE)|TRUNCATE)\b'; then
  deny "Database destructive operation"
fi

# ══════════════════════════════════════════════════════════════
# PASS THROUGH: Everything else requires user decision
# ══════════════════════════════════════════════════════════════
exit 0
