esphome:
  name: audiobook-player
  friendly_name: "Audiobook Player"
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Audiobook-Player"
    password: !secret fallback_password

captive_portal:

# SPI bus configuration for RC522
spi:
  clk_pin: D5   # GPIO14
  miso_pin: D6  # GPIO12
  mosi_pin: D7  # GPIO13

# RC522 RFID reader configuration
rc522_spi:
  cs_pin: D8    # GPIO15
  update_interval: 500ms

  # When a tag is detected, send it to Home Assistant
  on_tag:
    then:
      - homeassistant.tag_scanned: !lambda 'return x;'
      - logger.log:
          format: "Tag scanned: %s"
          args: ['x.c_str()']

  # When tag is removed
  on_tag_removed:
    then:
      - logger.log:
          format: "Tag removed: %s"
          args: ['x.c_str()']

# Binary sensors for buttons
binary_sensor:
  # Green button - Play
  - platform: gpio
    pin:
      number: D1  # GPIO5
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Play Button"
    id: play_button
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.audiobook_control
            data:
              action: play

  # Red button - Pause
  - platform: gpio
    pin:
      number: D2  # GPIO4
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Pause Button"
    id: pause_button
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.audiobook_control
            data:
              action: pause

# Status LED (optional - uses built-in LED)
status_led:
  pin:
    number: D4  # GPIO2 - Built-in LED
    inverted: true
