esphome:
  name: audiobook-player
  friendly_name: "Audiobook Player"

esp32:
  board: wemosbat
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password
    on_begin:
      then:
        - deep_sleep.prevent: deep_sleep_control

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Audiobook-Player"
    password: !secret fallback_password

captive_portal:

# Deep sleep configuration for power management
deep_sleep:
  id: deep_sleep_control
  run_duration: 2min        # Stay awake for 2 minutes after wake
  wakeup_pin: GPIO27        # Tilt switch wakes device
  wakeup_pin_mode: INVERT_WAKEUP  # Wake when tilt switch closes (connects to GND)

# SPI bus configuration for RC522
spi:
  clk_pin: GPIO18   # SCK - ESP32 VSPI default
  miso_pin: GPIO19  # MISO - ESP32 VSPI default
  mosi_pin: GPIO23  # MOSI - ESP32 VSPI default

# RC522 RFID reader configuration
rc522_spi:
  cs_pin: GPIO17    # CS/SDA - Changed from GPIO5 (strapping pin)
  update_interval: 500ms

  # When a tag is detected, send it to Home Assistant
  on_tag:
    then:
      - text_sensor.template.publish:
          id: last_rfid_tag
          state: !lambda 'return x;'
      - homeassistant.tag_scanned: !lambda 'return x;'
      - homeassistant.event:
          event: esphome.audiobook_triggered
          data:
            device_id: audiobook-player
            tag_id: !lambda 'return x;'
      - logger.log:
          format: "Tag scanned: %s"
          args: ['x.c_str()']
      - output.turn_on: status_led_output
      - delay: 300ms
      - output.turn_off: status_led_output

  # When tag is removed
  on_tag_removed:
    then:
      - text_sensor.template.publish:
          id: last_rfid_tag
          state: ""
      - logger.log:
          format: "Tag removed: %s"
          args: ['x.c_str()']

# Text sensor to store the last scanned RFID tag
text_sensor:
  - platform: template
    name: "Last RFID Tag"
    id: last_rfid_tag
    icon: "mdi:card-account-details"

# Binary sensors for buttons
binary_sensor:
  # Green button - Play
  - platform: gpio
    pin:
      number: GPIO32  # Available GPIO pin
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Play Button"
    id: play_button
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.audiobook_control
            data:
              action: play

  # Red button - Pause
  - platform: gpio
    pin:
      number: GPIO33  # Available GPIO pin
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Pause Button"
    id: pause_button
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms
    on_press:
      then:
        - homeassistant.event:
            event: esphome.audiobook_control
            data:
              action: pause

# Output for built-in LED to indicate RFID tag reads
output:
  - platform: gpio
    pin:
      number: GPIO16  # Built-in LED on WEMOS Battery ESP32
      inverted: true
    id: status_led_output
