// Auto-generated by tools/typst/generate-pin-defs.py
// Source: packages/robocar/unified/main/pin_config.h
//         packages/robocar/unified/version.txt
// Do not edit manually — regenerate with `just robocar-unified::gen-pin-defs`.

#let VERSION = "0.1.16"

// ── I2C Bus ──
#let I2C_SDA_PIN = 5
#let I2C_SCL_PIN = 6
#let I2C_FREQ_HZ = 400000
// ── TCA9548A Multiplexer ──
#let TCA9548A_ADDR = "0x70"
#let TCA_CH_PCA9685 = 0
#let TCA_CH_OLED = 1
#let TCA_CH_MCP23017 = 2
// ── PCA9685 PWM Driver ──
#let PCA9685_ADDR = "0x40"
#let PCA9685_FREQ_HZ = 200
// ── PCA9685 — LED Channels ──
#let PCA_CH_LED_LEFT_R = 0
#let PCA_CH_LED_LEFT_G = 1
#let PCA_CH_LED_LEFT_B = 2
#let PCA_CH_LED_RIGHT_R = 3
#let PCA_CH_LED_RIGHT_G = 4
#let PCA_CH_LED_RIGHT_B = 5
// ── PCA9685 — Servo Channels ──
#let PCA_CH_SERVO_PAN = 6
#let PCA_CH_SERVO_TILT = 7
// ── PCA9685 — Motor Channels ──
#let PCA_CH_MOTOR_R_IN1 = 8
#let PCA_CH_MOTOR_R_IN2 = 9
#let PCA_CH_MOTOR_R_PWM = 10
#let PCA_CH_MOTOR_L_IN1 = 11
#let PCA_CH_MOTOR_L_IN2 = 12
#let PCA_CH_MOTOR_L_PWM = 13
// ── Motor Control ──
#let MOTOR_STBY_PIN = 1
// ── MCP23017 GPIO Expander ──
#let MCP23017_ADDR = "0x20"
// ── SSD1306 OLED ──
#let OLED_ADDR = "0x3C"
#let OLED_WIDTH = 128
#let OLED_HEIGHT = 64
// ── Ultrasonic Rangefinder ──
#let ULTRIG_PIN = 3
#let ULECHO_PIN = 4
// ── Piezo Buzzer ──
#let PIEZO_PIN = 2
// ── MAX98357A I2S Audio ──
#let I2S_BCLK_PIN = 7
#let I2S_LRCLK_PIN = 8
#let I2S_DIN_PIN = 9
#let AUDIO_SAMPLE_RATE_HZ = 24000
