#!/usr/bin/env bash
# SessionStart hook: install development tools when running in Claude Code on the web.
# Idempotent: each tool is skipped if already on PATH.
# Generated by /configure-plugin:configure-web-session.
set -euo pipefail

if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  echo "[install_pkgs] Not a remote environment, skipping."
  exit 0
fi

INSTALL_DIR="${HOME}/.local/bin"
mkdir -p "$INSTALL_DIR"
export PATH="$INSTALL_DIR:$PATH"

has() { command -v "$1" >/dev/null 2>&1; }

# --- pre-commit (via pip) ---
if ! has pre-commit; then
  echo "[install_pkgs] Installing pre-commit..."
  pip install --user --quiet pre-commit
else
  echo "[install_pkgs] pre-commit already installed, skipping."
fi

# --- gitleaks (keep in lockstep with .pre-commit-config.yaml rev) ---
# renovate: datasource=github-releases depName=gitleaks/gitleaks extractVersion=^v(?<version>.+)$
GITLEAKS_VERSION="8.30.1"
if ! has gitleaks; then
  echo "[install_pkgs] Installing gitleaks ${GITLEAKS_VERSION}..."
  tmpdir=$(mktemp -d)
  curl -fsSL "https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz" | tar xz -C "${tmpdir}" gitleaks
  mv "${tmpdir}/gitleaks" "${INSTALL_DIR}/gitleaks"
  chmod +x "${INSTALL_DIR}/gitleaks"
  rm -rf "${tmpdir}"
else
  echo "[install_pkgs] gitleaks already installed, skipping."
fi

# --- just (latest stable) ---
# renovate: datasource=github-releases depName=casey/just
JUST_VERSION="1.52.0"
if ! has just; then
  echo "[install_pkgs] Installing just ${JUST_VERSION}..."
  tmpdir=$(mktemp -d)
  curl -fsSL "https://github.com/casey/just/releases/download/${JUST_VERSION}/just-${JUST_VERSION}-x86_64-unknown-linux-musl.tar.gz" | tar xz -C "${tmpdir}" just
  mv "${tmpdir}/just" "${INSTALL_DIR}/just"
  chmod +x "${INSTALL_DIR}/just"
  rm -rf "${tmpdir}"
else
  echo "[install_pkgs] just already installed, skipping."
fi

# --- cppcheck (apt; required by `just lint-c` / `just lint` for C/C++ analysis) ---
# Distro package, not a pinned binary release — no version pin to annotate.
if ! has cppcheck; then
  echo "[install_pkgs] Installing cppcheck..."
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq cppcheck
else
  echo "[install_pkgs] cppcheck already installed, skipping."
fi

# --- Summary ---
echo "[install_pkgs] Done. Available tools:"
for cmd in pre-commit gitleaks just cppcheck ; do
  if has "$cmd"; then
    echo "  $cmd: $(command -v "$cmd")"
  else
    echo "  $cmd: NOT FOUND (install failed)"
  fi
done
