/**
 * @file ota_manager.c
 * @brief OTA update manager for the single-board unified robocar
 *
 * Polls the web-flasher's published manifest (the same JSON the Pages site
 * and ESP Web Tools consume, generated by tools/generate-flasher-manifests.sh)
 * rather than the GitHub Releases API. See issue #539: esp_ghota called the
 * wrong API host, its filename match could never hit, and monorepo
 * release-please tags do not parse as semver — none of which is fixable by
 * configuration. The manifest carries a clean per-project version and the
 * app binary's path directly, so there is nothing left to parse out of a
 * GitHub API response.
 *
 * A dedicated FreeRTOS task blocks on either the OTA_CHECK_INTERVAL_MIN
 * periodic timeout or an explicit task notification (the MQTT check-now
 * nudge), then performs one manifest fetch + compare + (maybe) flash cycle.
 * Per .claude/rules/freertos-task-gotchas.md, any task making an HTTPS call
 * needs at least an 8 KB stack for the TLS handshake — this task is created
 * with OTA_TASK_STACK_SIZE, already 8192 in config.h.
 */

#include "ota_manager.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "cJSON.h"
#include "config.h"
#include "esp_app_desc.h"
#include "esp_crt_bundle.h"
#include "esp_http_client.h"
#include "esp_https_ota.h"
#include "esp_log.h"
#include "esp_ota_ops.h"
#include "esp_timer.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/timers.h"
#include "ota_interval.h"
#include "ota_version_compare.h"
#if MQTT_LOGGING_ENABLED
#include "mqtt_logger.h"
#endif

static const char *TAG = "OTA_Manager";

/** Core 1 — bursty, I/O-bound, same as camera_task/planner_task/network_task
 *  (see CLAUDE.md's Architecture section). Never Core 0: that core is
 *  reserved for the timing-sensitive motor/reactive-controller loop. */
#define OTA_TASK_CORE 1
/** manifest.json is a few hundred bytes (see web-flasher.md); this is
 *  generous headroom without putting a large buffer on the task stack. */
#define OTA_MANIFEST_BUF_SIZE 2048
/** Long enough for the Pages host + path + a project-scoped .bin filename. */
#define OTA_BIN_URL_BUF_SIZE 256
/** esp_app_get_description()->version is a fixed 32-byte field. */
#define OTA_VERSION_STR_BUF_SIZE 32

// OTA manager state
static TaskHandle_t s_ota_task_handle = NULL;
static bool s_ota_in_progress = false;
static bool s_firmware_valid_confirmed = false;
static TimerHandle_t s_stability_timer = NULL;

// Forward declarations
static void ota_task(void *arg);
static void run_update_check(void);
static void start_https_ota(const char *bin_url);
static esp_err_t fetch_manifest_json(char *buf, size_t buf_size, int *status_out);
static bool select_app_part_path(const cJSON *manifest, const char **path_out);
static bool resolve_relative_url(const char *base_url, const char *relative_path, char *out,
                                 size_t out_size);
static void ota_stability_timer_callback(TimerHandle_t xTimer);

#if MQTT_LOGGING_ENABLED
static void mqtt_ota_notify_handler(const char *topic, const char *data, int data_len);
#endif

esp_err_t ota_manager_init(void)
{
    ESP_LOGI(TAG, "Initializing OTA manager");
    ESP_LOGI(TAG, "Current firmware version: %s", ota_manager_get_version());

    BaseType_t created =
        xTaskCreatePinnedToCore(ota_task, "ota_task", OTA_TASK_STACK_SIZE, NULL, OTA_TASK_PRIORITY,
                                &s_ota_task_handle, OTA_TASK_CORE);
    if (created != pdPASS) {
        ESP_LOGE(TAG, "Failed to create OTA task");
        return ESP_FAIL;
    }

    ESP_LOGI(TAG, "OTA check task started (interval: %d min, manifest: %s)", OTA_CHECK_INTERVAL_MIN,
             OTA_MANIFEST_URL);

#if MQTT_LOGGING_ENABLED
    // Subscribe to MQTT OTA notification topic (a check-now nudge — see
    // mqtt_ota_notify_handler())
    mqtt_logger_subscribe(OTA_MQTT_NOTIFY_TOPIC, mqtt_ota_notify_handler);
    ESP_LOGI(TAG, "Subscribed to MQTT OTA topic: %s", OTA_MQTT_NOTIFY_TOPIC);
#endif

    // Clean up previous stability timer if re-initializing
    if (s_stability_timer) {
        xTimerStop(s_stability_timer, 0);
        xTimerDelete(s_stability_timer, pdMS_TO_TICKS(100));
        s_stability_timer = NULL;
    }

    // Start rollback protection stability timer
    s_stability_timer = xTimerCreate("ota_stability", pdMS_TO_TICKS(OTA_STABILITY_TIMEOUT_MS),
                                     pdFALSE, NULL, ota_stability_timer_callback);
    if (s_stability_timer) {
        xTimerStart(s_stability_timer, 0);
        ESP_LOGI(TAG, "Rollback stability timer started (%d ms)", OTA_STABILITY_TIMEOUT_MS);
    }

    ESP_LOGI(TAG, "OTA manager initialized successfully");
    return ESP_OK;
}

esp_err_t ota_manager_check_update(void)
{
    if (!s_ota_task_handle) {
        ESP_LOGE(TAG, "OTA manager not initialized");
        return ESP_ERR_INVALID_STATE;
    }

    if (s_ota_in_progress) {
        ESP_LOGW(TAG, "OTA update already in progress");
        return ESP_ERR_INVALID_STATE;
    }

    ESP_LOGI(TAG, "Triggering manual update check");
    // Wakes ota_task() immediately instead of waiting for the periodic
    // timeout — this is the MQTT check-now nudge's whole mechanism.
    xTaskNotifyGive(s_ota_task_handle);
    return ESP_OK;
}

const char *ota_manager_get_version(void)
{
    const esp_app_desc_t *app_desc = esp_app_get_description();
    return app_desc->version;
}

esp_err_t ota_manager_confirm_valid(void)
{
    if (s_firmware_valid_confirmed) {
        return ESP_OK;
    }

    esp_err_t ret = esp_ota_mark_app_valid_cancel_rollback();
    if (ret == ESP_OK) {
        s_firmware_valid_confirmed = true;
        ESP_LOGI(TAG, "Firmware marked as valid — rollback cancelled");
    } else {
        ESP_LOGW(TAG, "Failed to mark firmware valid: %s (may not be OTA boot)",
                 esp_err_to_name(ret));
    }
    return ret;
}

/**
 * Blocks on either the periodic interval or an explicit notification
 * (ota_manager_check_update(), driven by the MQTT nudge), then runs one
 * check. Either wake reason runs the same check — a check-now nudge that
 * arrives mid-interval does not skip the next periodic one; it just moves it.
 */
static void ota_task(void *arg)
{
    (void)arg;

    // pdMS_TO_TICKS() on this project's non-SMP FreeRTOS kernel computes
    // (ms * configTICK_RATE_HZ) / 1000 entirely in TickType_t (uint32_t), so
    // feeding it OTA_CHECK_INTERVAL_MIN converted to milliseconds overflows
    // before the division runs — see ota_interval.h. Do the multiply in a
    // 64-bit intermediate instead, and fail closed to a short, known-safe
    // interval (never a silent truncation) if it still would not fit.
    uint32_t interval_ticks_u32 = 0;
    TickType_t interval_ticks;
    if (ota_interval_ticks_from_minutes((uint32_t)OTA_CHECK_INTERVAL_MIN,
                                        (uint32_t)configTICK_RATE_HZ, &interval_ticks_u32)) {
        interval_ticks = (TickType_t)interval_ticks_u32;
    } else {
        ESP_LOGE(
            TAG,
            "OTA_CHECK_INTERVAL_MIN=%d overflows a tick count at %d Hz — falling back to %d ms",
            OTA_CHECK_INTERVAL_MIN, (int)configTICK_RATE_HZ, OTA_INTERVAL_OVERFLOW_FALLBACK_MS);
        interval_ticks = pdMS_TO_TICKS(OTA_INTERVAL_OVERFLOW_FALLBACK_MS);
    }

    for (;;) {
        ulTaskNotifyTake(pdTRUE, interval_ticks);
        run_update_check();
    }
}

/** HTTP response accumulator, same shape as gemini_http.c's — bounded copy
 *  into a caller-owned buffer, NUL-terminated, truncating (with a warning)
 *  rather than overrunning if the server sends more than expected. */
typedef struct {
    char *buf;
    size_t len;
    size_t cap;
} ota_http_acc_t;

static esp_err_t ota_http_event_handler(esp_http_client_event_t *evt)
{
    if (evt->event_id != HTTP_EVENT_ON_DATA) {
        return ESP_OK;
    }
    ota_http_acc_t *acc = (ota_http_acc_t *)evt->user_data;
    if (!acc || !acc->buf || !evt->data || evt->data_len <= 0) {
        return ESP_OK;
    }
    size_t avail = acc->cap - 1 - acc->len;
    size_t to_copy = ((size_t)evt->data_len < avail) ? (size_t)evt->data_len : avail;
    if (to_copy > 0) {
        memcpy(acc->buf + acc->len, evt->data, to_copy);
        acc->len += to_copy;
        acc->buf[acc->len] = '\0';
    }
    // cppcheck-suppress knownConditionTrueFalse // true when buffer fills (to_copy==avail<data_len)
    if (to_copy < (size_t)evt->data_len) {
        ESP_LOGW(TAG, "manifest response truncated — discarded %d bytes",
                 (int)((size_t)evt->data_len - to_copy));
    }
    return ESP_OK;
}

static esp_err_t fetch_manifest_json(char *buf, size_t buf_size, int *status_out)
{
    ota_http_acc_t acc = {.buf = buf, .len = 0, .cap = buf_size};
    buf[0] = '\0';

    esp_http_client_config_t cfg = {
        .url = OTA_MANIFEST_URL,
        .method = HTTP_METHOD_GET,
        .timeout_ms = OTA_HTTP_TIMEOUT_MS,
        .event_handler = ota_http_event_handler,
        .user_data = &acc,
        .crt_bundle_attach = esp_crt_bundle_attach,
    };

    esp_http_client_handle_t client = esp_http_client_init(&cfg);
    if (!client) {
        ESP_LOGE(TAG, "esp_http_client_init() failed for manifest fetch");
        return ESP_FAIL;
    }

    esp_err_t err = esp_http_client_perform(client);
    int status = esp_http_client_get_status_code(client);
    if (status_out) {
        *status_out = status;
    }
    esp_http_client_cleanup(client);

    if (err == ESP_OK && status != 200) {
        err = ESP_FAIL;
    }
    return err;
}

/**
 * The manifest's `builds[].parts[]` list is offsets-first (bootloader,
 * partition-table, optionally otadata, then the app), per
 * tools/generate-flasher-manifests.sh. The app binary is always the part
 * with the HIGHEST offset — this identifies it without hardcoding a filename
 * that would need to track appBinaryName from a flasher.json this firmware
 * never reads.
 */
static bool select_app_part_path(const cJSON *manifest, const char **path_out)
{
    const cJSON *builds = cJSON_GetObjectItemCaseSensitive(manifest, "builds");
    if (!cJSON_IsArray(builds)) {
        return false;
    }

    const cJSON *best_part = NULL;
    double best_offset = -1.0;

    const cJSON *build = NULL;
    cJSON_ArrayForEach(build, builds)
    {
        const cJSON *parts = cJSON_GetObjectItemCaseSensitive(build, "parts");
        if (!cJSON_IsArray(parts)) {
            continue;
        }
        const cJSON *part = NULL;
        cJSON_ArrayForEach(part, parts)
        {
            const cJSON *offset = cJSON_GetObjectItemCaseSensitive(part, "offset");
            const cJSON *path = cJSON_GetObjectItemCaseSensitive(part, "path");
            if (!cJSON_IsNumber(offset) || !cJSON_IsString(path) || !path->valuestring) {
                continue;
            }
            if (offset->valuedouble > best_offset) {
                best_offset = offset->valuedouble;
                best_part = path;
            }
        }
    }

    if (!best_part) {
        return false;
    }
    *path_out = best_part->valuestring;
    return true;
}

/**
 * Resolve a manifest part path relative to the manifest's OWN url, rather
 * than hardcoding a second copy of the Pages firmware directory — the part
 * path is everything after the manifest's final '/'.
 */
static bool resolve_relative_url(const char *base_url, const char *relative_path, char *out,
                                 size_t out_size)
{
    if (!base_url || !relative_path || !out || out_size == 0) {
        return false;
    }
    if (strstr(relative_path, "://") != NULL) {
        // Already absolute — pass through unchanged.
        return snprintf(out, out_size, "%s", relative_path) < (int)out_size;
    }

    const char *last_slash = strrchr(base_url, '/');
    if (!last_slash) {
        return false;
    }
    size_t dir_len = (size_t)(last_slash - base_url) + 1;  // include the slash
    if (dir_len >= out_size) {
        return false;
    }
    memcpy(out, base_url, dir_len);
    int written = snprintf(out + dir_len, out_size - dir_len, "%s", relative_path);
    return written > 0 && (dir_len + (size_t)written) < out_size;
}

static void run_update_check(void)
{
    ESP_LOGI(TAG, "Checking manifest for update: %s", OTA_MANIFEST_URL);

    char *manifest_buf = malloc(OTA_MANIFEST_BUF_SIZE);
    if (!manifest_buf) {
        ESP_LOGE(TAG, "Failed to allocate manifest buffer");
        return;
    }

    int status = 0;
    esp_err_t err = fetch_manifest_json(manifest_buf, OTA_MANIFEST_BUF_SIZE, &status);
    if (err != ESP_OK) {
        ESP_LOGW(TAG, "Manifest fetch failed: %s (HTTP %d)", esp_err_to_name(err), status);
        free(manifest_buf);
        return;
    }

    cJSON *manifest = cJSON_Parse(manifest_buf);
    free(manifest_buf);
    if (!manifest) {
        ESP_LOGW(TAG, "Manifest JSON parse failed");
        return;
    }

    const cJSON *version_node = cJSON_GetObjectItemCaseSensitive(manifest, "version");
    if (!cJSON_IsString(version_node) || !version_node->valuestring) {
        ESP_LOGW(TAG, "Manifest missing a usable \"version\" field");
        cJSON_Delete(manifest);
        return;
    }

    // Reject rather than silently truncate — a truncated string could parse
    // as a shorter, DIFFERENT version and compare as "newer" or "older" than
    // what the manifest actually published. See ota_version_fits().
    if (!ota_version_fits(version_node->valuestring, OTA_VERSION_STR_BUF_SIZE)) {
        ESP_LOGW(TAG,
                 "Manifest \"version\" is %zu bytes (max %d) — refusing to truncate; no update",
                 strlen(version_node->valuestring), OTA_VERSION_STR_BUF_SIZE - 1);
        cJSON_Delete(manifest);
        return;
    }

    char remote_version[OTA_VERSION_STR_BUF_SIZE];
    snprintf(remote_version, sizeof(remote_version), "%s", version_node->valuestring);
    const char *current_version = ota_manager_get_version();

    ota_version_compare_result_t cmp = ota_version_compare(current_version, remote_version);
    if (cmp != OTA_VERSION_COMPARE_UPDATE_AVAILABLE) {
        if (cmp == OTA_VERSION_COMPARE_INVALID) {
            ESP_LOGW(TAG, "Cannot compare versions (\"%s\" running vs \"%s\" manifest) — no update",
                     current_version, remote_version);
        } else {
            ESP_LOGI(TAG, "No update available (running %s, manifest %s)", current_version,
                     remote_version);
        }
        cJSON_Delete(manifest);
        return;
    }

    const char *part_path = NULL;
    char bin_url[OTA_BIN_URL_BUF_SIZE] = {0};
    bool resolved = select_app_part_path(manifest, &part_path) &&
                    resolve_relative_url(OTA_MANIFEST_URL, part_path, bin_url, sizeof(bin_url));
    cJSON_Delete(manifest);
    if (!resolved) {
        ESP_LOGE(TAG, "Manifest has no resolvable app binary part");
        return;
    }

    ESP_LOGI(TAG, "Update available: %s -> %s (%s)", current_version, remote_version, bin_url);
    start_https_ota(bin_url);
}

static void start_https_ota(const char *bin_url)
{
    s_ota_in_progress = true;

#if MQTT_LOGGING_ENABLED
    mqtt_logger_publish(OTA_MQTT_STATUS_TOPIC, "{\"status\":\"downloading\"}", 1, false);
#endif

    esp_http_client_config_t http_cfg = {
        .url = bin_url,
        .timeout_ms = OTA_HTTP_TIMEOUT_MS,
        .crt_bundle_attach = esp_crt_bundle_attach,
        .keep_alive_enable = true,
    };
    esp_https_ota_config_t ota_cfg = {
        .http_config = &http_cfg,
    };

    ESP_LOGI(TAG, "Starting firmware update from %s", bin_url);
    esp_err_t ret = esp_https_ota(&ota_cfg);
    s_ota_in_progress = false;

    if (ret == ESP_OK) {
        ESP_LOGI(TAG, "Firmware update complete — rebooting...");
#if MQTT_LOGGING_ENABLED
        mqtt_logger_publish(OTA_MQTT_STATUS_TOPIC, "{\"status\":\"rebooting\"}", 1, false);
#endif
        // Brief delay to allow the MQTT message to send
        vTaskDelay(pdMS_TO_TICKS(500));
        esp_restart();
    } else {
        ESP_LOGE(TAG, "esp_https_ota() failed: %s", esp_err_to_name(ret));
#if MQTT_LOGGING_ENABLED
        mqtt_logger_publish(OTA_MQTT_STATUS_TOPIC, "{\"status\":\"failed\"}", 1, false);
#endif
    }
}

static void ota_stability_timer_callback(TimerHandle_t xTimer)
{
    (void)xTimer;
    ESP_LOGI(TAG, "Stability timeout reached — confirming firmware validity");
    ota_manager_confirm_valid();
}

#if MQTT_LOGGING_ENABLED
static void mqtt_ota_notify_handler(const char *topic, const char *data, int data_len)
{
    ESP_LOGI(TAG, "MQTT OTA notification received on topic: %s", topic);
    ESP_LOGI(TAG, "Notification data: %.*s", data_len, data);

    // Rate limit: at most one check per 60 seconds
    static int64_t s_last_ota_check_time = 0;
    int64_t now = esp_timer_get_time();
    if (s_last_ota_check_time > 0 && (now - s_last_ota_check_time) < 60 * 1000000LL) {
        ESP_LOGW(TAG, "MQTT OTA trigger rate-limited, skipping");
        return;
    }
    s_last_ota_check_time = now;

    esp_err_t ret = ota_manager_check_update();
    if (ret != ESP_OK) {
        ESP_LOGW(TAG, "Failed to trigger update check: %s", esp_err_to_name(ret));
    }
}
#endif
