name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    uses: laurigates/.github/.github/workflows/reusable-release-please.yml@main
    secrets:
      MY_RELEASE_PLEASE_TOKEN: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
